name: Main Push Deployment with tests and docker image build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  test-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - run: npm install
      - run: npm test

  build-docker-image:
    needs: test-changes
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/simple-nodejs-app:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/simple-nodejs-app:latest

  deploy-and-health-check:
    needs: build-docker-image
    runs-on: ubuntu-latest

    steps:
      - name: Pull and deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            python3 << EOF
            import subprocess 
            import time
            import json


            def verify_container_running():
                result = subprocess.run(f"docker ps --filter name=simple-node-api --format '{{{{.Names}}}} {{{{.Status}}}}'",
                                    shell=True,
                                    capture_output=True,
                                    text=True
                                )

                print(result.stdout)

                if "simple-node-api" in result.stdout and "Up" in result.stdout:
                    print("Container is currently running.")
                    return True
                
                else:
                    print("Container is not running.")
                    return False
                

            def stop_and_remove_container():
                stop_container = subprocess.run("docker stop simple-node-api",
                                                shell=True,
                                                capture_output=True,
                                                text=True
                                            )
                if stop_container.returncode == 0:
                    print("Container stopped successfully.")
                    remove_container = subprocess.run("docker rm -f simple-node-api",
                                                shell=True,
                                                capture_output=True,
                                                text=True
                                                )
                    if remove_container.returncode == 0:
                        print("Container removed successfully.")
                        return True
                    else:
                        print("Failed to remove the container.")
                        return False
                
                else: 
                    print("Failed to stop the container.")
                    return False
                
            def pull_container():
                pull_image = subprocess.run("docker pull ghcr.io/${{ github.repository_owner }}/simple-nodejs-app:${{ github.sha }}",
                                                    shell=True,
                                                    capture_output=True,
                                                    text=True
                                                )
                if pull_image.returncode == 0:
                    print("Image pulled successfully.")
                    return True
                else:
                    print("Failed to pull the image.")
                    return False
                
            def run_container():
                run_container = subprocess.run("docker run -d -p 4000:4000 --name simple-node-api ghcr.io/${{ github.repository_owner }}/simple-nodejs-app:${{ github.sha }}",
                                                    shell=True,
                                                    capture_output=True,
                                                    text=True
                                                )
                
                time.sleep(2)
                check_running = subprocess.run(f"docker ps --filter name=simple-node-api --format '{{{{.Names}}}} {{{{.Status}}}}'",
                                    shell=True,
                                    capture_output=True,
                                    text=True
                                )
                if "simple-node-api" in check_running.stdout and "Up" in check_running.stdout:
                    print("Container started successfully.")
                    print(f"{check_running.stdout}")
                    return True
                else:
                    print("Failed to start the container.")
                    print(f"{check_running.stdout}")
                    return False
                

            def health_check():
                time.sleep(10)  # Wait for a few seconds to allow the container to initialize
                health_check = subprocess.run("curl -f http://localhost:4000/health",
                                                        shell=True,
                                                        capture_output=True,
                                                        text=True
                                                    )
                if health_check.returncode == 0:
                    try:
                        health_data = json.loads(health_check.stdout)
                        print(f"Health Check Response: {health_data}")
                        if health_data.get("status") == "healthy":
                            print("Health check passed.")
                            return True
                        else:
                            print("Health check status is not healthy.")
                            return False
                    except json.JSONDecodeError:
                        print("Failed to parse health check response as JSON.")
                        return False
                    
                else:
                    print("Health check failed.")
                    return False


            def main():
                
                container_running = verify_container_running()

                if container_running:
                    stopped_and_removed = stop_and_remove_container()
                    if not stopped_and_removed:
                        exit(1)
                        

                steps = [
                    ("Pull Image", pull_container),
                    ("Run Container", run_container),
                    ("Health Check", health_check)
                ]      

                for step_name, step_func in steps:
                    print(f"Starting step: {step_name}")
                    step_success = step_func()
                    if not step_success:
                        print(f"Step: {step_name} failed.")
                        exit(1)
                    print(f"Step: {step_name} completed successfully.")

                print("Deployment completed successfully.")
                exit(0)
                        

            main()
            
            EOF
            
            
    
